// source: singing.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

goog.exportSymbol('singingZH_snet_singingZH.Answer', null, global);
goog.exportSymbol('singingZH_snet_singingZH.Query', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
singingZH_snet_singingZH.Query = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(singingZH_snet_singingZH.Query, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  singingZH_snet_singingZH.Query.displayName = 'singingZH_snet_singingZH.Query';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
singingZH_snet_singingZH.Answer = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(singingZH_snet_singingZH.Answer, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  singingZH_snet_singingZH.Answer.displayName = 'singingZH_snet_singingZH.Answer';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
singingZH_snet_singingZH.Query.prototype.toObject = function(opt_includeInstance) {
  return singingZH_snet_singingZH.Query.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!singingZH_snet_singingZH.Query} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
singingZH_snet_singingZH.Query.toObject = function(includeInstance, msg) {
  var f, obj = {
    text: jspb.Message.getFieldWithDefault(msg, 1, ""),
    midiFile: msg.getMidiFile_asB64(),
    normalize: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!singingZH_snet_singingZH.Query}
 */
singingZH_snet_singingZH.Query.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new singingZH_snet_singingZH.Query;
  return singingZH_snet_singingZH.Query.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!singingZH_snet_singingZH.Query} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!singingZH_snet_singingZH.Query}
 */
singingZH_snet_singingZH.Query.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setText(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setMidiFile(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setNormalize(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
singingZH_snet_singingZH.Query.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  singingZH_snet_singingZH.Query.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!singingZH_snet_singingZH.Query} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
singingZH_snet_singingZH.Query.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getText();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMidiFile_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
  f = message.getNormalize();
  if (f !== 0.0) {
    writer.writeFloat(
      3,
      f
    );
  }
};


/**
 * optional string text = 1;
 * @return {string}
 */
singingZH_snet_singingZH.Query.prototype.getText = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!singingZH_snet_singingZH.Query} returns this
 */
singingZH_snet_singingZH.Query.prototype.setText = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional bytes midi_file = 2;
 * @return {!(string|Uint8Array)}
 */
singingZH_snet_singingZH.Query.prototype.getMidiFile = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes midi_file = 2;
 * This is a type-conversion wrapper around `getMidiFile()`
 * @return {string}
 */
singingZH_snet_singingZH.Query.prototype.getMidiFile_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getMidiFile()));
};


/**
 * optional bytes midi_file = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getMidiFile()`
 * @return {!Uint8Array}
 */
singingZH_snet_singingZH.Query.prototype.getMidiFile_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getMidiFile()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!singingZH_snet_singingZH.Query} returns this
 */
singingZH_snet_singingZH.Query.prototype.setMidiFile = function(value) {
  return jspb.Message.setProto3BytesField(this, 2, value);
};


/**
 * optional float normalize = 3;
 * @return {number}
 */
singingZH_snet_singingZH.Query.prototype.getNormalize = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!singingZH_snet_singingZH.Query} returns this
 */
singingZH_snet_singingZH.Query.prototype.setNormalize = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
singingZH_snet_singingZH.Answer.prototype.toObject = function(opt_includeInstance) {
  return singingZH_snet_singingZH.Answer.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!singingZH_snet_singingZH.Answer} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
singingZH_snet_singingZH.Answer.toObject = function(includeInstance, msg) {
  var f, obj = {
    outputAudio: msg.getOutputAudio_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!singingZH_snet_singingZH.Answer}
 */
singingZH_snet_singingZH.Answer.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new singingZH_snet_singingZH.Answer;
  return singingZH_snet_singingZH.Answer.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!singingZH_snet_singingZH.Answer} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!singingZH_snet_singingZH.Answer}
 */
singingZH_snet_singingZH.Answer.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setOutputAudio(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
singingZH_snet_singingZH.Answer.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  singingZH_snet_singingZH.Answer.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!singingZH_snet_singingZH.Answer} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
singingZH_snet_singingZH.Answer.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOutputAudio_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
};


/**
 * optional bytes output_audio = 1;
 * @return {!(string|Uint8Array)}
 */
singingZH_snet_singingZH.Answer.prototype.getOutputAudio = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes output_audio = 1;
 * This is a type-conversion wrapper around `getOutputAudio()`
 * @return {string}
 */
singingZH_snet_singingZH.Answer.prototype.getOutputAudio_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getOutputAudio()));
};


/**
 * optional bytes output_audio = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getOutputAudio()`
 * @return {!Uint8Array}
 */
singingZH_snet_singingZH.Answer.prototype.getOutputAudio_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getOutputAudio()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!singingZH_snet_singingZH.Answer} returns this
 */
singingZH_snet_singingZH.Answer.prototype.setOutputAudio = function(value) {
  return jspb.Message.setProto3BytesField(this, 1, value);
};


goog.object.extend(exports, singingZH_snet_singingZH);
