export const VOICES = [
    { id: 0, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 1, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 2, gender: 'man', tone: 'low', age: 'old' },
    { id: 3, gender: 'man', tone: 'low', age: 'old' },
    { id: 4, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 5, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 6, gender: 'man', tone: 'low', age: 'old' },
    { id: 7, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 8, gender: 'man', tone: 'mid', age: 'young' },
    { id: 9, gender: 'man', tone: 'mid', age: 'old' },
    { id: 10, gender: 'woman', tone: 'high', age: 'old' },
    { id: 11, gender: 'woman', tone: 'high', age: 'old' },
    { id: 12, gender: 'woman', tone: 'high', age: 'young' },
    { id: 13, gender: 'man', tone: 'mid', age: 'young' },
    { id: 14, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 15, gender: 'man', tone: 'mid', age: 'old' },
    { id: 16, gender: 'woman', tone: 'high', age: 'young' },
    { id: 17, gender: 'man', tone: 'mid', age: 'old' },
    { id: 18, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 19, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 20, gender: 'man', tone: 'mid', age: 'young' },
    { id: 21, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 22, gender: 'woman', tone: 'high', age: 'old' },
    { id: 23, gender: 'woman', tone: 'high', age: 'young' },
    { id: 24, gender: 'man', tone: 'mid', age: 'young' },
    { id: 25, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 26, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 27, gender: 'man', tone: 'mid', age: 'young' },
    { id: 28, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 29, gender: 'woman', tone: 'high', age: 'young' },
    { id: 30, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 31, gender: 'man', tone: 'mid', age: 'old' },
    { id: 32, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 33, gender: 'woman', tone: 'high', age: 'young' },
    { id: 34, gender: 'man', tone: 'mid', age: 'young' },
    { id: 35, gender: 'man', tone: 'high', age: 'young' },
    { id: 36, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 37, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 38, gender: 'man', tone: 'mid', age: 'old' },
    { id: 39, gender: 'woman', tone: 'high', age: 'old' },
    { id: 40, gender: 'man', tone: 'mid', age: 'old' },
    { id: 41, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 42, gender: 'man', tone: 'mid', age: 'old' },
    { id: 43, gender: 'man', tone: 'mid', age: 'old' },
    { id: 44, gender: 'man', tone: 'mid', age: 'old' },
    { id: 45, gender: 'man', tone: 'mid', age: 'old' },
    { id: 46, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 47, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 48, gender: 'man', tone: 'mid', age: 'young' },
    { id: 49, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 50, gender: 'man', tone: 'mid', age: 'old' },
    { id: 51, gender: 'man', tone: 'mid', age: 'young' },
    { id: 52, gender: 'man', tone: 'mid', age: 'young' },
    { id: 53, gender: 'woman', tone: 'high', age: 'old' },
    { id: 54, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 55, gender: 'man', tone: 'mid', age: 'young' },
    { id: 56, gender: 'man', tone: 'mid', age: 'young' },
    { id: 57, gender: 'man', tone: 'mid', age: 'young' },
    { id: 58, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 59, gender: 'woman', tone: 'high', age: 'young' },
    { id: 60, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 61, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 62, gender: 'woman', tone: 'high', age: 'young' },
    { id: 63, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 64, gender: 'man', tone: 'mid', age: 'young' },
    { id: 65, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 66, gender: 'man', tone: 'mid', age: 'old' },
    { id: 67, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 68, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 69, gender: 'woman', tone: 'high', age: 'young' },
    { id: 70, gender: 'man', tone: 'mid', age: 'young' },
    { id: 71, gender: 'man', tone: 'mid', age: 'old' },
    { id: 72, gender: 'man', tone: 'mid', age: 'old' },
    { id: 73, gender: 'man', tone: 'high', age: 'young' },
    { id: 74, gender: 'man', tone: 'mid', age: 'old' },
    { id: 75, gender: 'man', tone: 'mid', age: 'old' },
    { id: 76, gender: 'woman', tone: 'high', age: 'old' },
    { id: 77, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 78, gender: 'woman', tone: 'high', age: 'young' },
    { id: 79, gender: 'man', tone: 'mid', age: 'young' },
    { id: 80, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 81, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 82, gender: 'woman', tone: 'high', age: 'young' },
    { id: 83, gender: 'man', tone: 'mid', age: 'young' },
    { id: 84, gender: 'man', tone: 'mid', age: 'old' },
    { id: 85, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 86, gender: 'woman', tone: 'high', age: 'young' },
    { id: 87, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 88, gender: 'man', tone: 'mid', age: 'young' },
    { id: 89, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 90, gender: 'man', tone: 'mid', age: 'old' },
    { id: 91, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 92, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 93, gender: 'woman', tone: 'high', age: 'young' },
    { id: 94, gender: 'man', tone: 'high', age: 'young' },
    { id: 95, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 96, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 97, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 98, gender: 'woman', tone: 'high', age: 'young' },
    { id: 99, gender: 'man', tone: 'mid', age: 'old' },
    { id: 100, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 101, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 102, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 103, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 104, gender: 'woman', tone: 'high', age: 'old' },
    { id: 105, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 106, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 107, gender: 'man', tone: 'mid', age: 'young' },
    { id: 108, gender: 'man', tone: 'mid', age: 'old' },
    { id: 109, gender: 'man', tone: 'mid', age: 'old' },
    { id: 110, gender: 'man', tone: 'mid', age: 'old' },
    { id: 111, gender: 'man', tone: 'mid', age: 'young' },
    { id: 112, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 113, gender: 'man', tone: 'mid', age: 'old' },
    { id: 114, gender: 'man', tone: 'high', age: 'young' },
    { id: 115, gender: 'man', tone: 'mid', age: 'old' },
    { id: 116, gender: 'woman', tone: 'high', age: 'young' },
    { id: 117, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 118, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 119, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 120, gender: 'man', tone: 'mid', age: 'young' },
    { id: 121, gender: 'man', tone: 'mid', age: 'old' },
    { id: 122, gender: 'woman', tone: 'high', age: 'young' },
    { id: 123, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 124, gender: 'man', tone: 'low', age: 'old' },
    { id: 125, gender: 'man', tone: 'mid', age: 'old' },
    { id: 126, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 127, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 128, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 129, gender: 'man', tone: 'mid', age: 'young' },
    { id: 130, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 131, gender: 'man', tone: 'mid', age: 'old' },
    { id: 132, gender: 'man', tone: 'mid', age: 'young' },
    { id: 133, gender: 'man', tone: 'mid', age: 'young' },
    { id: 134, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 135, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 136, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 137, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 138, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 139, gender: 'woman', tone: 'high', age: 'young' },
    { id: 140, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 141, gender: 'man', tone: 'mid', age: 'old' },
    { id: 142, gender: 'man', tone: 'mid', age: 'old' },
    { id: 143, gender: 'woman', tone: 'high', age: 'old' },
    { id: 144, gender: 'man', tone: 'mid', age: 'old' },
    { id: 145, gender: 'woman', tone: 'high', age: 'old' },
    { id: 146, gender: 'man', tone: 'mid', age: 'old' },
    { id: 147, gender: 'man', tone: 'mid', age: 'old' },
    { id: 148, gender: 'man', tone: 'mid', age: 'old' },
    { id: 149, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 150, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 151, gender: 'man', tone: 'mid', age: 'old' },
    { id: 152, gender: 'man', tone: 'mid', age: 'old' },
    { id: 153, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 154, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 155, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 156, gender: 'woman', tone: 'high', age: 'young' },
    { id: 157, gender: 'woman', tone: 'high', age: 'old' },
    { id: 158, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 159, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 160, gender: 'man', tone: 'mid', age: 'old' },
    { id: 161, gender: 'man', tone: 'mid', age: 'old' },
    { id: 162, gender: 'woman', tone: 'high', age: 'old' },
    { id: 163, gender: 'man', tone: 'mid', age: 'young' },
    { id: 164, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 165, gender: 'man', tone: 'mid', age: 'young' },
    { id: 166, gender: 'woman', tone: 'high', age: 'young' },
    { id: 167, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 168, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 169, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 170, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 171, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 172, gender: 'man', tone: 'mid', age: 'young' },
    { id: 173, gender: 'man', tone: 'mid', age: 'young' },
    { id: 174, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 175, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 176, gender: 'man', tone: 'mid', age: 'old' },
    { id: 177, gender: 'man', tone: 'mid', age: 'young' },
    { id: 178, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 179, gender: 'woman', tone: 'high', age: 'young' },
    { id: 180, gender: 'man', tone: 'mid', age: 'old' },
    { id: 181, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 182, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 183, gender: 'woman', tone: 'high', age: 'young' },
    { id: 184, gender: 'man', tone: 'mid', age: 'young' },
    { id: 185, gender: 'woman', tone: 'high', age: 'young' },
    { id: 186, gender: 'woman', tone: 'high', age: 'young' },
    { id: 187, gender: 'man', tone: 'mid', age: 'young' },
    { id: 188, gender: 'man', tone: 'mid', age: 'young' },
    { id: 189, gender: 'man', tone: 'mid', age: 'young' },
    { id: 190, gender: 'man', tone: 'mid', age: 'old' },
    { id: 191, gender: 'man', tone: 'mid', age: 'old' },
    { id: 192, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 193, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 194, gender: 'man', tone: 'mid', age: 'young' },
    { id: 195, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 196, gender: 'man', tone: 'mid', age: 'old' },
    { id: 197, gender: 'man', tone: 'high', age: 'young' },
    { id: 198, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 199, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 200, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 201, gender: 'man', tone: 'mid', age: 'old' },
    { id: 202, gender: 'woman', tone: 'high', age: 'old' },
    { id: 203, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 204, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 205, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 206, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 207, gender: 'man', tone: 'mid', age: 'old' },
    { id: 208, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 209, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 210, gender: 'woman', tone: 'high', age: 'young' },
    { id: 211, gender: 'man', tone: 'low', age: 'old' },
    { id: 212, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 213, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 214, gender: 'man', tone: 'high', age: 'old' },
    { id: 215, gender: 'woman', tone: 'high', age: 'young' },
    { id: 216, gender: 'woman', tone: 'high', age: 'young' },
    { id: 217, gender: 'man', tone: 'low', age: 'old' },
    { id: 218, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 219, gender: 'woman', tone: 'high', age: 'young' },
    { id: 220, gender: 'man', tone: 'mid', age: 'old' },
    { id: 221, gender: 'man', tone: 'mid', age: 'old' },
    { id: 222, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 223, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 224, gender: 'man', tone: 'mid', age: 'old' },
    { id: 225, gender: 'woman', tone: 'high', age: 'young' },
    { id: 226, gender: 'man', tone: 'mid', age: 'old' },
    { id: 227, gender: 'man', tone: 'mid', age: 'young' },
    { id: 228, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 229, gender: 'woman', tone: 'high', age: 'old' },
    { id: 230, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 231, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 232, gender: 'man', tone: 'low', age: 'old' },
    { id: 233, gender: 'man', tone: 'mid', age: 'old' },
    { id: 234, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 235, gender: 'man', tone: 'mid', age: 'old' },
    { id: 236, gender: 'man', tone: 'low', age: 'old' },
    { id: 237, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 238, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 239, gender: 'man', tone: 'mid', age: 'young' },
    { id: 240, gender: 'man', tone: 'mid', age: 'old' },
    { id: 241, gender: 'man', tone: 'low', age: 'old' },
    { id: 242, gender: 'man', tone: 'mid', age: 'old' },
    { id: 243, gender: 'man', tone: 'low', age: 'old' },
    { id: 244, gender: 'man', tone: 'mid', age: 'old' },
    { id: 245, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 246, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 247, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 248, gender: 'man', tone: 'mid', age: 'old' },
    { id: 249, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 250, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 251, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 252, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 253, gender: 'woman', tone: 'high', age: 'old' },
    { id: 254, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 255, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 256, gender: 'woman', tone: 'low', age: 'old' },
    { id: 257, gender: 'man', tone: 'low', age: 'old' },
    { id: 258, gender: 'man', tone: 'mid', age: 'young' },
    { id: 259, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 260, gender: 'man', tone: 'mid', age: 'young' },
    { id: 261, gender: 'man', tone: 'mid', age: 'young' },
    { id: 262, gender: 'man', tone: 'mid', age: 'young' },
    { id: 263, gender: 'man', tone: 'low', age: 'old' },
    { id: 264, gender: 'man', tone: 'low', age: 'old' },
    { id: 265, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 266, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 267, gender: 'man', tone: 'mid', age: 'old' },
    { id: 268, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 269, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 270, gender: 'woman', tone: 'mid', age: 'old' },
    { id: 271, gender: 'man', tone: 'mid', age: 'young' },
    { id: 272, gender: 'man', tone: 'mid', age: 'young' },
    { id: 273, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 274, gender: 'man', tone: 'mid', age: 'old' },
    { id: 275, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 276, gender: 'woman', tone: 'mid', age: 'young' },
    { id: 277, gender: 'man', tone: 'mid', age: 'old' },
    { id: 278, gender: 'woman', tone: 'mid', age: 'old' },
    // { id: 279, gender: 'man', tone: 'mid', age: 'young' },
    // { id: 280, gender: 'woman', tone: 'mid', age: 'old' },
    // { id: 281, gender: 'woman', tone: 'high', age: 'old' },
    // { id: 282, gender: 'man', tone: 'high', age: 'young' },
    // { id: 283, gender: 'woman', tone: 'mid', age: 'young' },
    // { id: 284, gender: 'woman', tone: 'mid', age: 'young' },
    // { id: 285, gender: 'woman', tone: 'high', age: 'young' },
    // { id: 286, gender: 'woman', tone: 'high', age: 'young' },
    // { id: 287, gender: 'woman', tone: 'high', age: 'young' },
    // { id: 288, gender: 'woman', tone: 'mid', age: 'young' },
    // { id: 289, gender: 'woman', tone: 'high', age: 'young' },
    // { id: 290, gender: 'woman', tone: 'low', age: 'young' },
    // { id: 291, gender: 'woman', tone: 'mid', age: 'old' },
    // { id: 292, gender: 'woman', tone: 'mid', age: 'old' },
    // { id: 293, gender: 'woman', tone: 'mid', age: 'old' },
    // { id: 294, gender: 'woman', tone: 'high', age: 'young' },
    // { id: 295, gender: 'woman', tone: 'high', age: 'young' },
    // { id: 296, gender: 'woman', tone: 'high', age: 'young' },
    // { id: 297, gender: 'woman', tone: 'high', age: 'young' },
    // { id: 298, gender: 'woman', tone: 'high', age: 'young' },
    // { id: 299, gender: 'woman', tone: 'mid', age: 'old' },
    // { id: 300, gender: 'woman', tone: 'mid', age: 'old' },
    // { id: 302, gender: 'man', tone: 'high', age: 'old' },
    // { id: 303, gender: 'woman', tone: 'high', age: 'old' },
    // { id: 304, gender: 'woman', tone: 'mid', age: 'old' },
    // { id: 305, gender: 'man', tone: 'mid', age: 'old' },
    // { id: 306, gender: 'woman', tone: 'high', age: 'young' },
    // { id: 307, gender: 'woman', tone: 'mid', age: 'old' },
    // { id: 308, gender: 'woman', tone: 'mid', age: 'young' },
    // { id: 309, gender: 'man', tone: 'mid', age: 'old' },
    // { id: 310, gender: 'man', tone: 'mid', age: 'old' },
    // { id: 311, gender: 'woman', tone: 'high', age: 'young' },
    // { id: 312, gender: 'man', tone: 'mid', age: 'old' },
    // { id: 313, gender: 'woman', tone: 'mid', age: 'young' },
    // { id: 314, gender: 'woman', tone: 'mid', age: 'young' },
    // { id: 315, gender: 'woman', tone: 'mid', age: 'old' },
    // { id: 316, gender: 'woman', tone: 'low', age: 'old' },
    // { id: 317, gender: 'man', tone: 'mid', age: 'young' },
    // { id: 318, gender: 'man', tone: 'mid', age: 'young' },
    // { id: 320, gender: 'woman', tone: 'high', age: 'young' },
    // { id: 321, gender: 'man', tone: 'mid', age: 'old' },
];

export const DROPDOWN_PARAMETERS = {
    emotion: {
        1: {
            label: 'Neutral',
            value: '1',
        },
        2: {
            label: 'Happy',
            value: '2',
        },
        3: {
            label: 'Sad',
            value: '3',
        },
        4: {
            label: 'Angry',
            value: '4',
        },
        5: {
            label: 'Fear',
            value: '5',
        },
        6: {
            label: 'Disgust',
            value: '6',
        },
        7: {
            label: 'Surprise',
            value: '7',
        },
    },
    gender: {
        man: { label: 'Man', value: 'man' },
        woman: { label: 'Woman', value: 'woman' },
    },
    age: {
        young: { label: 'Young', value: 'young' },
        old: { label: 'Old', value: 'old' },
    },
    tone: {
        low: { label: 'Low', value: 'low' },
        mid: { label: 'Mid', value: 'mid' },
        high: { label: 'High', value: 'high' },
    },
};
