// source: neural_image_generation.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

goog.exportSymbol('neural_image_generation_naint_neural_image_generation.Image', null, global);
goog.exportSymbol('neural_image_generation_naint_neural_image_generation.Text', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
neural_image_generation_naint_neural_image_generation.Text = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(neural_image_generation_naint_neural_image_generation.Text, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  neural_image_generation_naint_neural_image_generation.Text.displayName = 'neural_image_generation_naint_neural_image_generation.Text';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
neural_image_generation_naint_neural_image_generation.Image = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(neural_image_generation_naint_neural_image_generation.Image, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  neural_image_generation_naint_neural_image_generation.Image.displayName = 'neural_image_generation_naint_neural_image_generation.Image';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
neural_image_generation_naint_neural_image_generation.Text.prototype.toObject = function(opt_includeInstance) {
  return neural_image_generation_naint_neural_image_generation.Text.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!neural_image_generation_naint_neural_image_generation.Text} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
neural_image_generation_naint_neural_image_generation.Text.toObject = function(includeInstance, msg) {
  var f, obj = {
    sentence: jspb.Message.getFieldWithDefault(msg, 1, ""),
    model: jspb.Message.getFieldWithDefault(msg, 2, ""),
    seedval: jspb.Message.getFieldWithDefault(msg, 3, 0),
    nImages: jspb.Message.getFieldWithDefault(msg, 4, 0),
    steps: jspb.Message.getFieldWithDefault(msg, 5, 0),
    promptStyle: jspb.Message.getFieldWithDefault(msg, 6, ""),
    image: msg.getImage_asB64(),
    negativePrompt: jspb.Message.getFieldWithDefault(msg, 8, ""),
    h: jspb.Message.getFieldWithDefault(msg, 9, 0),
    w: jspb.Message.getFieldWithDefault(msg, 10, 0),
    guidanceScale: jspb.Message.getFloatingPointFieldWithDefault(msg, 11, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!neural_image_generation_naint_neural_image_generation.Text}
 */
neural_image_generation_naint_neural_image_generation.Text.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new neural_image_generation_naint_neural_image_generation.Text;
  return neural_image_generation_naint_neural_image_generation.Text.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!neural_image_generation_naint_neural_image_generation.Text} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!neural_image_generation_naint_neural_image_generation.Text}
 */
neural_image_generation_naint_neural_image_generation.Text.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSentence(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setModel(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSeedval(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNImages(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSteps(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setPromptStyle(value);
      break;
    case 7:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setImage(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setNegativePrompt(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setH(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setW(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setGuidanceScale(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
neural_image_generation_naint_neural_image_generation.Text.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  neural_image_generation_naint_neural_image_generation.Text.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!neural_image_generation_naint_neural_image_generation.Text} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
neural_image_generation_naint_neural_image_generation.Text.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSentence();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getModel();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getSeedval();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getNImages();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getSteps();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getPromptStyle();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getImage_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      7,
      f
    );
  }
  f = message.getNegativePrompt();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getH();
  if (f !== 0) {
    writer.writeInt32(
      9,
      f
    );
  }
  f = message.getW();
  if (f !== 0) {
    writer.writeInt32(
      10,
      f
    );
  }
  f = message.getGuidanceScale();
  if (f !== 0.0) {
    writer.writeDouble(
      11,
      f
    );
  }
};


/**
 * optional string sentence = 1;
 * @return {string}
 */
neural_image_generation_naint_neural_image_generation.Text.prototype.getSentence = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!neural_image_generation_naint_neural_image_generation.Text} returns this
 */
neural_image_generation_naint_neural_image_generation.Text.prototype.setSentence = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string model = 2;
 * @return {string}
 */
neural_image_generation_naint_neural_image_generation.Text.prototype.getModel = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!neural_image_generation_naint_neural_image_generation.Text} returns this
 */
neural_image_generation_naint_neural_image_generation.Text.prototype.setModel = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 seedVal = 3;
 * @return {number}
 */
neural_image_generation_naint_neural_image_generation.Text.prototype.getSeedval = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!neural_image_generation_naint_neural_image_generation.Text} returns this
 */
neural_image_generation_naint_neural_image_generation.Text.prototype.setSeedval = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 n_images = 4;
 * @return {number}
 */
neural_image_generation_naint_neural_image_generation.Text.prototype.getNImages = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!neural_image_generation_naint_neural_image_generation.Text} returns this
 */
neural_image_generation_naint_neural_image_generation.Text.prototype.setNImages = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int32 steps = 5;
 * @return {number}
 */
neural_image_generation_naint_neural_image_generation.Text.prototype.getSteps = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!neural_image_generation_naint_neural_image_generation.Text} returns this
 */
neural_image_generation_naint_neural_image_generation.Text.prototype.setSteps = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional string prompt_style = 6;
 * @return {string}
 */
neural_image_generation_naint_neural_image_generation.Text.prototype.getPromptStyle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!neural_image_generation_naint_neural_image_generation.Text} returns this
 */
neural_image_generation_naint_neural_image_generation.Text.prototype.setPromptStyle = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional bytes image = 7;
 * @return {!(string|Uint8Array)}
 */
neural_image_generation_naint_neural_image_generation.Text.prototype.getImage = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * optional bytes image = 7;
 * This is a type-conversion wrapper around `getImage()`
 * @return {string}
 */
neural_image_generation_naint_neural_image_generation.Text.prototype.getImage_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getImage()));
};


/**
 * optional bytes image = 7;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getImage()`
 * @return {!Uint8Array}
 */
neural_image_generation_naint_neural_image_generation.Text.prototype.getImage_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getImage()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!neural_image_generation_naint_neural_image_generation.Text} returns this
 */
neural_image_generation_naint_neural_image_generation.Text.prototype.setImage = function(value) {
  return jspb.Message.setProto3BytesField(this, 7, value);
};


/**
 * optional string negative_prompt = 8;
 * @return {string}
 */
neural_image_generation_naint_neural_image_generation.Text.prototype.getNegativePrompt = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!neural_image_generation_naint_neural_image_generation.Text} returns this
 */
neural_image_generation_naint_neural_image_generation.Text.prototype.setNegativePrompt = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional int32 H = 9;
 * @return {number}
 */
neural_image_generation_naint_neural_image_generation.Text.prototype.getH = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!neural_image_generation_naint_neural_image_generation.Text} returns this
 */
neural_image_generation_naint_neural_image_generation.Text.prototype.setH = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional int32 W = 10;
 * @return {number}
 */
neural_image_generation_naint_neural_image_generation.Text.prototype.getW = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!neural_image_generation_naint_neural_image_generation.Text} returns this
 */
neural_image_generation_naint_neural_image_generation.Text.prototype.setW = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional double guidance_scale = 11;
 * @return {number}
 */
neural_image_generation_naint_neural_image_generation.Text.prototype.getGuidanceScale = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 11, 0.0));
};


/**
 * @param {number} value
 * @return {!neural_image_generation_naint_neural_image_generation.Text} returns this
 */
neural_image_generation_naint_neural_image_generation.Text.prototype.setGuidanceScale = function(value) {
  return jspb.Message.setProto3FloatField(this, 11, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
neural_image_generation_naint_neural_image_generation.Image.prototype.toObject = function(opt_includeInstance) {
  return neural_image_generation_naint_neural_image_generation.Image.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!neural_image_generation_naint_neural_image_generation.Image} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
neural_image_generation_naint_neural_image_generation.Image.toObject = function(includeInstance, msg) {
  var f, obj = {
    image1: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!neural_image_generation_naint_neural_image_generation.Image}
 */
neural_image_generation_naint_neural_image_generation.Image.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new neural_image_generation_naint_neural_image_generation.Image;
  return neural_image_generation_naint_neural_image_generation.Image.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!neural_image_generation_naint_neural_image_generation.Image} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!neural_image_generation_naint_neural_image_generation.Image}
 */
neural_image_generation_naint_neural_image_generation.Image.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setImage1(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
neural_image_generation_naint_neural_image_generation.Image.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  neural_image_generation_naint_neural_image_generation.Image.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!neural_image_generation_naint_neural_image_generation.Image} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
neural_image_generation_naint_neural_image_generation.Image.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getImage1();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string image1 = 1;
 * @return {string}
 */
neural_image_generation_naint_neural_image_generation.Image.prototype.getImage1 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!neural_image_generation_naint_neural_image_generation.Image} returns this
 */
neural_image_generation_naint_neural_image_generation.Image.prototype.setImage1 = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


goog.object.extend(exports, neural_image_generation_naint_neural_image_generation);
